#!/usr/bin/env python3
"""
Seed exchange_ranked_symbols + symbols_master with full global universe.

Uses hardcoded index constituents (S&P 500, NIFTY 100, FTSE 100, etc.)
No external API required — deterministic and reliable.

Usage:
  cd backend
  source venv/bin/activate
  python scripts/seed_global_universe.py
"""
import sys
from pathlib import Path
from datetime import datetime, timezone

sys.path.insert(0, str(Path(__file__).parent.parent))

from dotenv import load_dotenv
load_dotenv(Path(__file__).parent.parent / ".env")

from app.db.database import SessionLocal
from app.models.exchange_ranked_symbol import ExchangeRankedSymbol
from app.models.symbols_master import SymbolsMaster

# ── Exchange universe data ──────────────────────────────────────────────────
# Format: (symbol, name, sector, industry, currency, exchange_code)

US_STOCKS = [
    # Technology (60)
    ("AAPL","Apple Inc.","Technology","Consumer Electronics","USD","NASDAQ"),
    ("MSFT","Microsoft Corp.","Technology","Software","USD","NASDAQ"),
    ("NVDA","NVIDIA Corp.","Technology","Semiconductors","USD","NASDAQ"),
    ("GOOGL","Alphabet Inc.","Communication Services","Internet Content","USD","NASDAQ"),
    ("GOOG","Alphabet Inc. C","Communication Services","Internet Content","USD","NASDAQ"),
    ("META","Meta Platforms","Communication Services","Internet Content","USD","NASDAQ"),
    ("AVGO","Broadcom Inc.","Technology","Semiconductors","USD","NASDAQ"),
    ("TSLA","Tesla Inc.","Consumer Cyclical","Auto Manufacturers","USD","NASDAQ"),
    ("ORCL","Oracle Corp.","Technology","Software","USD","NYSE"),
    ("CRM","Salesforce Inc.","Technology","Software","USD","NYSE"),
    ("AMD","Advanced Micro Devices","Technology","Semiconductors","USD","NASDAQ"),
    ("ADBE","Adobe Inc.","Technology","Software","USD","NASDAQ"),
    ("NOW","ServiceNow Inc.","Technology","Software","USD","NYSE"),
    ("QCOM","QUALCOMM Inc.","Technology","Semiconductors","USD","NASDAQ"),
    ("TXN","Texas Instruments","Technology","Semiconductors","USD","NASDAQ"),
    ("AMAT","Applied Materials","Technology","Semiconductor Equipment","USD","NASDAQ"),
    ("INTC","Intel Corp.","Technology","Semiconductors","USD","NASDAQ"),
    ("MU","Micron Technology","Technology","Semiconductors","USD","NASDAQ"),
    ("LRCX","Lam Research","Technology","Semiconductor Equipment","USD","NASDAQ"),
    ("KLAC","KLA Corp.","Technology","Semiconductor Equipment","USD","NASDAQ"),
    ("NFLX","Netflix Inc.","Communication Services","Entertainment","USD","NASDAQ"),
    ("INTU","Intuit Inc.","Technology","Software","USD","NASDAQ"),
    ("PANW","Palo Alto Networks","Technology","Cybersecurity","USD","NASDAQ"),
    ("CRWD","CrowdStrike","Technology","Cybersecurity","USD","NASDAQ"),
    ("FTNT","Fortinet Inc.","Technology","Cybersecurity","USD","NASDAQ"),
    ("DDOG","Datadog Inc.","Technology","Software","USD","NASDAQ"),
    ("SNOW","Snowflake Inc.","Technology","Cloud Software","USD","NYSE"),
    ("NET","Cloudflare Inc.","Technology","Networking","USD","NYSE"),
    ("CSCO","Cisco Systems","Technology","Networking","USD","NASDAQ"),
    ("IBM","IBM Corp.","Technology","IT Services","USD","NYSE"),
    ("ACN","Accenture plc","Technology","IT Services","USD","NYSE"),
    ("IT","Gartner Inc.","Technology","IT Services","USD","NYSE"),
    ("CTSH","Cognizant Technology","Technology","IT Services","USD","NASDAQ"),
    ("HPQ","HP Inc.","Technology","Computer Hardware","USD","NYSE"),
    ("HPE","Hewlett Packard Enterprise","Technology","Computer Hardware","USD","NYSE"),
    ("DELL","Dell Technologies","Technology","Computer Hardware","USD","NYSE"),
    ("STX","Seagate Technology","Technology","Data Storage","USD","NASDAQ"),
    ("WDC","Western Digital","Technology","Data Storage","USD","NASDAQ"),
    ("NTAP","NetApp Inc.","Technology","Data Storage","USD","NASDAQ"),
    ("FFIV","F5 Inc.","Technology","Networking","USD","NASDAQ"),
    ("CDW","CDW Corp.","Technology","IT Services","USD","NASDAQ"),
    ("MSI","Motorola Solutions","Technology","Communications","USD","NYSE"),
    ("ANSS","ANSYS Inc.","Technology","Software","USD","NASDAQ"),
    ("PTC","PTC Inc.","Technology","Software","USD","NASDAQ"),
    ("CDNS","Cadence Design","Technology","EDA Software","USD","NASDAQ"),
    ("SNPS","Synopsys Inc.","Technology","EDA Software","USD","NASDAQ"),
    ("TER","Teradyne Inc.","Technology","Semiconductor Equipment","USD","NASDAQ"),
    ("MCHP","Microchip Technology","Technology","Semiconductors","USD","NASDAQ"),
    ("ADI","Analog Devices","Technology","Semiconductors","USD","NASDAQ"),
    ("ON","ON Semiconductor","Technology","Semiconductors","USD","NASDAQ"),
    ("MPWR","Monolithic Power Systems","Technology","Semiconductors","USD","NASDAQ"),
    ("ENPH","Enphase Energy","Technology","Solar","USD","NASDAQ"),
    ("SEDG","SolarEdge Technologies","Technology","Solar","USD","NASDAQ"),
    ("KEYS","Keysight Technologies","Technology","Test Equipment","USD","NYSE"),
    ("TRMB","Trimble Inc.","Technology","GPS/Survey","USD","NASDAQ"),
    ("EPAM","EPAM Systems","Technology","IT Services","USD","NYSE"),
    ("OKTA","Okta Inc.","Technology","Cybersecurity","USD","NASDAQ"),
    ("ZS","Zscaler Inc.","Technology","Cybersecurity","USD","NASDAQ"),
    ("TTWO","Take-Two Interactive","Technology","Video Games","USD","NASDAQ"),
    ("EA","Electronic Arts","Technology","Video Games","USD","NASDAQ"),
    # Healthcare (40)
    ("LLY","Eli Lilly","Healthcare","Pharmaceuticals","USD","NYSE"),
    ("UNH","UnitedHealth Group","Healthcare","Health Insurance","USD","NYSE"),
    ("JNJ","Johnson & Johnson","Healthcare","Pharmaceuticals","USD","NYSE"),
    ("ABBV","AbbVie Inc.","Healthcare","Biotechnology","USD","NYSE"),
    ("MRK","Merck & Co.","Healthcare","Pharmaceuticals","USD","NYSE"),
    ("PFE","Pfizer Inc.","Healthcare","Pharmaceuticals","USD","NYSE"),
    ("TMO","Thermo Fisher Scientific","Healthcare","Medical Devices","USD","NYSE"),
    ("ABT","Abbott Laboratories","Healthcare","Medical Devices","USD","NYSE"),
    ("DHR","Danaher Corp.","Healthcare","Medical Devices","USD","NYSE"),
    ("CVS","CVS Health","Healthcare","Drug Stores","USD","NYSE"),
    ("ELV","Elevance Health","Healthcare","Health Insurance","USD","NYSE"),
    ("CI","Cigna Group","Healthcare","Health Insurance","USD","NYSE"),
    ("HUM","Humana Inc.","Healthcare","Health Insurance","USD","NYSE"),
    ("MCK","McKesson Corp.","Healthcare","Drug Distribution","USD","NYSE"),
    ("CAH","Cardinal Health","Healthcare","Drug Distribution","USD","NYSE"),
    ("BMY","Bristol-Myers Squibb","Healthcare","Pharmaceuticals","USD","NYSE"),
    ("AMGN","Amgen Inc.","Healthcare","Biotechnology","USD","NASDAQ"),
    ("GILD","Gilead Sciences","Healthcare","Biotechnology","USD","NASDAQ"),
    ("REGN","Regeneron Pharma","Healthcare","Biotechnology","USD","NASDAQ"),
    ("VRTX","Vertex Pharmaceuticals","Healthcare","Biotechnology","USD","NASDAQ"),
    ("ISRG","Intuitive Surgical","Healthcare","Medical Devices","USD","NASDAQ"),
    ("SYK","Stryker Corp.","Healthcare","Medical Devices","USD","NYSE"),
    ("BSX","Boston Scientific","Healthcare","Medical Devices","USD","NYSE"),
    ("MDT","Medtronic plc","Healthcare","Medical Devices","USD","NYSE"),
    ("BDX","Becton Dickinson","Healthcare","Medical Devices","USD","NYSE"),
    ("ZBH","Zimmer Biomet","Healthcare","Medical Devices","USD","NYSE"),
    ("BAX","Baxter International","Healthcare","Medical Devices","USD","NYSE"),
    ("IQV","IQVIA Holdings","Healthcare","Healthcare IT","USD","NYSE"),
    ("CNC","Centene Corp.","Healthcare","Health Insurance","USD","NYSE"),
    ("MOH","Molina Healthcare","Healthcare","Health Insurance","USD","NYSE"),
    ("HCA","HCA Healthcare","Healthcare","Hospital Operators","USD","NYSE"),
    ("THC","Tenet Healthcare","Healthcare","Hospital Operators","USD","NYSE"),
    ("DGX","Quest Diagnostics","Healthcare","Diagnostics","USD","NYSE"),
    ("LH","Laboratory Corp.","Healthcare","Diagnostics","USD","NYSE"),
    ("BIIB","Biogen Inc.","Healthcare","Biotechnology","USD","NASDAQ"),
    ("MRNA","Moderna Inc.","Healthcare","Biotechnology","USD","NASDAQ"),
    ("ZTS","Zoetis Inc.","Healthcare","Animal Health","USD","NYSE"),
    ("IDXX","IDEXX Laboratories","Healthcare","Animal Health","USD","NASDAQ"),
    ("WAT","Waters Corp.","Healthcare","Instruments","USD","NYSE"),
    ("HOLX","Hologic Inc.","Healthcare","Medical Devices","USD","NASDAQ"),
    # Financials (45)
    ("BRK.B","Berkshire Hathaway B","Financials","Diversified Financial","USD","NYSE"),
    ("JPM","JPMorgan Chase","Financials","Banks","USD","NYSE"),
    ("BAC","Bank of America","Financials","Banks","USD","NYSE"),
    ("WFC","Wells Fargo","Financials","Banks","USD","NYSE"),
    ("GS","Goldman Sachs","Financials","Investment Banking","USD","NYSE"),
    ("MS","Morgan Stanley","Financials","Investment Banking","USD","NYSE"),
    ("C","Citigroup Inc.","Financials","Banks","USD","NYSE"),
    ("USB","U.S. Bancorp","Financials","Banks","USD","NYSE"),
    ("PNC","PNC Financial","Financials","Banks","USD","NYSE"),
    ("TFC","Truist Financial","Financials","Banks","USD","NYSE"),
    ("COF","Capital One Financial","Financials","Credit Cards","USD","NYSE"),
    ("AXP","American Express","Financials","Credit Cards","USD","NYSE"),
    ("V","Visa Inc.","Financials","Payment Processing","USD","NYSE"),
    ("MA","Mastercard Inc.","Financials","Payment Processing","USD","NYSE"),
    ("PYPL","PayPal Holdings","Financials","Payment Processing","USD","NASDAQ"),
    ("FI","Fiserv Inc.","Financials","Fintech","USD","NASDAQ"),
    ("FIS","Fidelity National Info","Financials","Fintech","USD","NYSE"),
    ("GPN","Global Payments","Financials","Fintech","USD","NYSE"),
    ("SPGI","S&P Global Inc.","Financials","Financial Data","USD","NYSE"),
    ("MCO","Moody's Corp.","Financials","Financial Data","USD","NYSE"),
    ("ICE","Intercontinental Exchange","Financials","Exchanges","USD","NYSE"),
    ("CME","CME Group","Financials","Exchanges","USD","NASDAQ"),
    ("CBOE","Cboe Global Markets","Financials","Exchanges","USD","CBOE"),
    ("BLK","BlackRock Inc.","Financials","Asset Management","USD","NYSE"),
    ("SCHW","Charles Schwab","Financials","Brokerage","USD","NYSE"),
    ("AMP","Ameriprise Financial","Financials","Asset Management","USD","NYSE"),
    ("IVZ","Invesco Ltd.","Financials","Asset Management","USD","NYSE"),
    ("TROW","T. Rowe Price","Financials","Asset Management","USD","NASDAQ"),
    ("PRU","Prudential Financial","Financials","Insurance","USD","NYSE"),
    ("MET","MetLife Inc.","Financials","Insurance","USD","NYSE"),
    ("AFL","Aflac Inc.","Financials","Insurance","USD","NYSE"),
    ("ALL","Allstate Corp.","Financials","Insurance","USD","NYSE"),
    ("PGR","Progressive Corp.","Financials","Insurance","USD","NYSE"),
    ("TRV","Travelers Companies","Financials","Insurance","USD","NYSE"),
    ("CB","Chubb Ltd.","Financials","Insurance","USD","NYSE"),
    ("HIG","Hartford Financial","Financials","Insurance","USD","NYSE"),
    ("RE","Everest Re Group","Financials","Reinsurance","USD","NYSE"),
    ("RJF","Raymond James Financial","Financials","Brokerage","USD","NYSE"),
    ("STT","State Street Corp.","Financials","Custodian Banks","USD","NYSE"),
    ("BK","Bank of New York Mellon","Financials","Custodian Banks","USD","NYSE"),
    ("MTB","M&T Bank Corp.","Financials","Banks","USD","NYSE"),
    ("FITB","Fifth Third Bancorp","Financials","Banks","USD","NASDAQ"),
    ("RF","Regions Financial","Financials","Banks","USD","NYSE"),
    ("HBAN","Huntington Bancshares","Financials","Banks","USD","NASDAQ"),
    ("KEY","KeyCorp","Financials","Banks","USD","NYSE"),
    # Consumer Cyclical (30)
    ("AMZN","Amazon.com Inc.","Consumer Cyclical","E-Commerce","USD","NASDAQ"),
    ("HD","Home Depot","Consumer Cyclical","Home Improvement","USD","NYSE"),
    ("LOW","Lowe's Companies","Consumer Cyclical","Home Improvement","USD","NYSE"),
    ("NKE","Nike Inc.","Consumer Cyclical","Footwear","USD","NYSE"),
    ("MCD","McDonald's Corp.","Consumer Cyclical","Restaurants","USD","NYSE"),
    ("SBUX","Starbucks Corp.","Consumer Cyclical","Restaurants","USD","NASDAQ"),
    ("YUM","Yum! Brands","Consumer Cyclical","Restaurants","USD","NYSE"),
    ("CMG","Chipotle Mexican Grill","Consumer Cyclical","Restaurants","USD","NYSE"),
    ("DPZ","Domino's Pizza","Consumer Cyclical","Restaurants","USD","NASDAQ"),
    ("F","Ford Motor","Consumer Cyclical","Auto Manufacturers","USD","NYSE"),
    ("GM","General Motors","Consumer Cyclical","Auto Manufacturers","USD","NYSE"),
    ("TJX","TJX Companies","Consumer Cyclical","Apparel Retail","USD","NYSE"),
    ("ROST","Ross Stores","Consumer Cyclical","Apparel Retail","USD","NASDAQ"),
    ("BURL","Burlington Stores","Consumer Cyclical","Apparel Retail","USD","NYSE"),
    ("GPS","Gap Inc.","Consumer Cyclical","Apparel Retail","USD","NYSE"),
    ("AZO","AutoZone Inc.","Consumer Cyclical","Auto Parts","USD","NYSE"),
    ("ORLY","O'Reilly Automotive","Consumer Cyclical","Auto Parts","USD","NASDAQ"),
    ("AAP","Advance Auto Parts","Consumer Cyclical","Auto Parts","USD","NYSE"),
    ("TSCO","Tractor Supply","Consumer Cyclical","Farm & Ranch","USD","NASDAQ"),
    ("POOL","Pool Corp.","Consumer Cyclical","Wholesale","USD","NASDAQ"),
    ("LVS","Las Vegas Sands","Consumer Cyclical","Casinos","USD","NYSE"),
    ("MGM","MGM Resorts","Consumer Cyclical","Casinos","USD","NYSE"),
    ("WYNN","Wynn Resorts","Consumer Cyclical","Casinos","USD","NASDAQ"),
    ("HLT","Hilton Worldwide","Consumer Cyclical","Hotels","USD","NYSE"),
    ("MAR","Marriott International","Consumer Cyclical","Hotels","USD","NASDAQ"),
    ("H","Hyatt Hotels","Consumer Cyclical","Hotels","USD","NYSE"),
    ("CCL","Carnival Corp.","Consumer Cyclical","Cruise Lines","USD","NYSE"),
    ("RCL","Royal Caribbean","Consumer Cyclical","Cruise Lines","USD","NYSE"),
    ("NCLH","Norwegian Cruise Line","Consumer Cyclical","Cruise Lines","USD","NYSE"),
    ("UAL","United Airlines","Consumer Cyclical","Airlines","USD","NASDAQ"),
    # Consumer Defensive (20)
    ("WMT","Walmart Inc.","Consumer Defensive","Discount Stores","USD","NYSE"),
    ("COST","Costco Wholesale","Consumer Defensive","Wholesale","USD","NASDAQ"),
    ("PG","Procter & Gamble","Consumer Defensive","Household Products","USD","NYSE"),
    ("KO","Coca-Cola Co.","Consumer Defensive","Beverages","USD","NYSE"),
    ("PEP","PepsiCo Inc.","Consumer Defensive","Beverages","USD","NASDAQ"),
    ("PM","Philip Morris","Consumer Defensive","Tobacco","USD","NYSE"),
    ("MO","Altria Group","Consumer Defensive","Tobacco","USD","NYSE"),
    ("STZ","Constellation Brands","Consumer Defensive","Beverages-Alcohol","USD","NYSE"),
    ("BUD","Anheuser-Busch InBev","Consumer Defensive","Beverages-Alcohol","USD","NYSE"),
    ("TAP","Molson Coors","Consumer Defensive","Beverages-Alcohol","USD","NYSE"),
    ("CL","Colgate-Palmolive","Consumer Defensive","Household Products","USD","NYSE"),
    ("KMB","Kimberly-Clark","Consumer Defensive","Household Products","USD","NYSE"),
    ("CHD","Church & Dwight","Consumer Defensive","Household Products","USD","NYSE"),
    ("CLX","Clorox Co.","Consumer Defensive","Household Products","USD","NYSE"),
    ("EL","Estee Lauder","Consumer Defensive","Cosmetics","USD","NYSE"),
    ("KR","Kroger Co.","Consumer Defensive","Grocery Stores","USD","NYSE"),
    ("SYY","Sysco Corp.","Consumer Defensive","Food Distribution","USD","NYSE"),
    ("CAG","Conagra Brands","Consumer Defensive","Packaged Foods","USD","NYSE"),
    ("CPB","Campbell Soup","Consumer Defensive","Packaged Foods","USD","NYSE"),
    ("GIS","General Mills","Consumer Defensive","Packaged Foods","USD","NYSE"),
    # Industrials (30)
    ("CAT","Caterpillar Inc.","Industrials","Farm & Heavy Equipment","USD","NYSE"),
    ("DE","Deere & Company","Industrials","Farm & Heavy Equipment","USD","NYSE"),
    ("BA","Boeing Co.","Industrials","Aerospace & Defense","USD","NYSE"),
    ("RTX","RTX Corp.","Industrials","Aerospace & Defense","USD","NYSE"),
    ("LMT","Lockheed Martin","Industrials","Aerospace & Defense","USD","NYSE"),
    ("NOC","Northrop Grumman","Industrials","Aerospace & Defense","USD","NYSE"),
    ("GD","General Dynamics","Industrials","Aerospace & Defense","USD","NYSE"),
    ("HII","Huntington Ingalls","Industrials","Aerospace & Defense","USD","NYSE"),
    ("TDG","TransDigm Group","Industrials","Aerospace Components","USD","NYSE"),
    ("HWM","Howmet Aerospace","Industrials","Aerospace Components","USD","NYSE"),
    ("GE","GE Aerospace","Industrials","Aerospace Engines","USD","NYSE"),
    ("HON","Honeywell International","Industrials","Conglomerates","USD","NASDAQ"),
    ("MMM","3M Company","Industrials","Conglomerates","USD","NYSE"),
    ("EMR","Emerson Electric","Industrials","Industrial Machinery","USD","NYSE"),
    ("ROK","Rockwell Automation","Industrials","Industrial Machinery","USD","NYSE"),
    ("ITW","Illinois Tool Works","Industrials","Industrial Machinery","USD","NASDAQ"),
    ("ETN","Eaton Corp.","Industrials","Electrical Equipment","USD","NYSE"),
    ("PH","Parker-Hannifin","Industrials","Industrial Machinery","USD","NYSE"),
    ("DOV","Dover Corp.","Industrials","Industrial Machinery","USD","NYSE"),
    ("XYL","Xylem Inc.","Industrials","Water Equipment","USD","NYSE"),
    ("FDX","FedEx Corp.","Industrials","Delivery Services","USD","NYSE"),
    ("UPS","United Parcel Service","Industrials","Delivery Services","USD","NYSE"),
    ("R","Ryder System","Industrials","Rental & Leasing","USD","NYSE"),
    ("CSX","CSX Corp.","Industrials","Railroads","USD","NASDAQ"),
    ("NSC","Norfolk Southern","Industrials","Railroads","USD","NYSE"),
    ("UNP","Union Pacific","Industrials","Railroads","USD","NYSE"),
    ("DAL","Delta Air Lines","Industrials","Airlines","USD","NYSE"),
    ("LUV","Southwest Airlines","Industrials","Airlines","USD","NYSE"),
    ("AAL","American Airlines","Industrials","Airlines","USD","NASDAQ"),
    ("EXPD","Expeditors International","Industrials","Air Freight","USD","NASDAQ"),
    # Energy (20)
    ("XOM","Exxon Mobil","Energy","Oil & Gas Integrated","USD","NYSE"),
    ("CVX","Chevron Corp.","Energy","Oil & Gas Integrated","USD","NYSE"),
    ("COP","ConocoPhillips","Energy","Oil & Gas E&P","USD","NYSE"),
    ("EOG","EOG Resources","Energy","Oil & Gas E&P","USD","NYSE"),
    ("PXD","Pioneer Natural Resources","Energy","Oil & Gas E&P","USD","NYSE"),
    ("DVN","Devon Energy","Energy","Oil & Gas E&P","USD","NYSE"),
    ("FANG","Diamondback Energy","Energy","Oil & Gas E&P","USD","NASDAQ"),
    ("MPC","Marathon Petroleum","Energy","Oil & Gas Refining","USD","NYSE"),
    ("VLO","Valero Energy","Energy","Oil & Gas Refining","USD","NYSE"),
    ("PSX","Phillips 66","Energy","Oil & Gas Refining","USD","NYSE"),
    ("OXY","Occidental Petroleum","Energy","Oil & Gas E&P","USD","NYSE"),
    ("APA","APA Corp.","Energy","Oil & Gas E&P","USD","NASDAQ"),
    ("HAL","Halliburton Co.","Energy","Oil & Gas Services","USD","NYSE"),
    ("SLB","SLB (Schlumberger)","Energy","Oil & Gas Services","USD","NYSE"),
    ("BKR","Baker Hughes","Energy","Oil & Gas Services","USD","NASDAQ"),
    ("KMI","Kinder Morgan","Energy","Oil & Gas Pipelines","USD","NYSE"),
    ("WMB","Williams Companies","Energy","Oil & Gas Pipelines","USD","NYSE"),
    ("OKE","ONEOK Inc.","Energy","Oil & Gas Pipelines","USD","NYSE"),
    ("LNG","Cheniere Energy","Energy","LNG","USD","NYSE"),
    ("CVI","CVR Energy","Energy","Oil & Gas Refining","USD","NYSE"),
    # Utilities (15)
    ("NEE","NextEra Energy","Utilities","Electric Utilities","USD","NYSE"),
    ("SO","Southern Company","Utilities","Electric Utilities","USD","NYSE"),
    ("DUK","Duke Energy","Utilities","Electric Utilities","USD","NYSE"),
    ("D","Dominion Energy","Utilities","Electric Utilities","USD","NYSE"),
    ("AEP","American Electric Power","Utilities","Electric Utilities","USD","NASDAQ"),
    ("EXC","Exelon Corp.","Utilities","Electric Utilities","USD","NASDAQ"),
    ("XEL","Xcel Energy","Utilities","Electric Utilities","USD","NASDAQ"),
    ("WEC","WEC Energy Group","Utilities","Electric Utilities","USD","NYSE"),
    ("ES","Eversource Energy","Utilities","Electric Utilities","USD","NYSE"),
    ("AWK","American Water Works","Utilities","Water Utilities","USD","NYSE"),
    ("PPL","PPL Corp.","Utilities","Electric Utilities","USD","NYSE"),
    ("ETR","Entergy Corp.","Utilities","Electric Utilities","USD","NYSE"),
    ("FE","FirstEnergy Corp.","Utilities","Electric Utilities","USD","NYSE"),
    ("PCG","PG&E Corp.","Utilities","Electric Utilities","USD","NYSE"),
    ("EIX","Edison International","Utilities","Electric Utilities","USD","NYSE"),
    # Real Estate (15)
    ("PLD","Prologis Inc.","Real Estate","Industrial REITs","USD","NYSE"),
    ("AMT","American Tower","Real Estate","Telecom REITs","USD","NYSE"),
    ("CCI","Crown Castle","Real Estate","Telecom REITs","USD","NYSE"),
    ("EQIX","Equinix Inc.","Real Estate","Data Center REITs","USD","NASDAQ"),
    ("PSA","Public Storage","Real Estate","Self-Storage REITs","USD","NYSE"),
    ("EQR","Equity Residential","Real Estate","Apartment REITs","USD","NYSE"),
    ("AVB","AvalonBay Communities","Real Estate","Apartment REITs","USD","NYSE"),
    ("O","Realty Income","Real Estate","Net Lease REITs","USD","NYSE"),
    ("VICI","VICI Properties","Real Estate","Gaming REITs","USD","NYSE"),
    ("WY","Weyerhaeuser Co.","Real Estate","Timber REITs","USD","NYSE"),
    ("VTR","Ventas Inc.","Real Estate","Health Care REITs","USD","NYSE"),
    ("WELL","Welltower Inc.","Real Estate","Health Care REITs","USD","NYSE"),
    ("ARE","Alexandria Real Estate","Real Estate","Life Science REITs","USD","NYSE"),
    ("BXP","BXP Inc.","Real Estate","Office REITs","USD","NYSE"),
    ("SPG","Simon Property Group","Real Estate","Mall REITs","USD","NYSE"),
    # Materials (15)
    ("LIN","Linde plc","Materials","Specialty Chemicals","USD","NASDAQ"),
    ("APD","Air Products","Materials","Specialty Chemicals","USD","NYSE"),
    ("ECL","Ecolab Inc.","Materials","Specialty Chemicals","USD","NYSE"),
    ("SHW","Sherwin-Williams","Materials","Specialty Chemicals","USD","NYSE"),
    ("PPG","PPG Industries","Materials","Specialty Chemicals","USD","NYSE"),
    ("DD","DuPont de Nemours","Materials","Specialty Chemicals","USD","NYSE"),
    ("NEM","Newmont Corp.","Materials","Gold","USD","NYSE"),
    ("FCX","Freeport-McMoRan","Materials","Copper","USD","NYSE"),
    ("NUE","Nucor Corp.","Materials","Steel","USD","NYSE"),
    ("STLD","Steel Dynamics","Materials","Steel","USD","NASDAQ"),
    ("ALB","Albemarle Corp.","Materials","Specialty Chemicals","USD","NYSE"),
    ("CF","CF Industries","Materials","Agricultural Chemicals","USD","NYSE"),
    ("MOS","Mosaic Company","Materials","Agricultural Chemicals","USD","NYSE"),
    ("VMC","Vulcan Materials","Materials","Construction Materials","USD","NYSE"),
    ("MLM","Martin Marietta","Materials","Construction Materials","USD","NYSE"),
    # Communication Services (10)
    ("CHTR","Charter Communications","Communication Services","Cable TV","USD","NASDAQ"),
    ("CMCSA","Comcast Corp.","Communication Services","Cable TV","USD","NASDAQ"),
    ("T","AT&T Inc.","Communication Services","Telecom","USD","NYSE"),
    ("VZ","Verizon Communications","Communication Services","Telecom","USD","NYSE"),
    ("TMUS","T-Mobile US","Communication Services","Telecom","USD","NASDAQ"),
    ("DIS","Walt Disney Co.","Communication Services","Entertainment","USD","NYSE"),
    ("PARA","Paramount Global","Communication Services","Entertainment","USD","NASDAQ"),
    ("WBD","Warner Bros. Discovery","Communication Services","Entertainment","USD","NASDAQ"),
    ("FOXA","Fox Corp. A","Communication Services","Broadcasting","USD","NASDAQ"),
    ("OMC","Omnicom Group","Communication Services","Advertising","USD","NYSE"),
]

INDIA_STOCKS = [
    # NIFTY 50 + NIFTY NEXT 50
    ("RELIANCE.NS","Reliance Industries","Energy","Oil & Gas Integrated","INR","NSE"),
    ("TCS.NS","Tata Consultancy Services","Technology","IT Services","INR","NSE"),
    ("HDFCBANK.NS","HDFC Bank","Financials","Banks","INR","NSE"),
    ("ICICIBANK.NS","ICICI Bank","Financials","Banks","INR","NSE"),
    ("INFY.NS","Infosys Ltd.","Technology","IT Services","INR","NSE"),
    ("HINDUNILVR.NS","Hindustan Unilever","Consumer Defensive","Household Products","INR","NSE"),
    ("ITC.NS","ITC Ltd.","Consumer Defensive","Tobacco","INR","NSE"),
    ("SBIN.NS","State Bank of India","Financials","Banks","INR","NSE"),
    ("BHARTIARTL.NS","Bharti Airtel","Communication Services","Telecom","INR","NSE"),
    ("KOTAKBANK.NS","Kotak Mahindra Bank","Financials","Banks","INR","NSE"),
    ("LT.NS","Larsen & Toubro","Industrials","Engineering","INR","NSE"),
    ("HCLTECH.NS","HCL Technologies","Technology","IT Services","INR","NSE"),
    ("ASIANPAINT.NS","Asian Paints","Materials","Specialty Chemicals","INR","NSE"),
    ("MARUTI.NS","Maruti Suzuki","Consumer Cyclical","Auto Manufacturers","INR","NSE"),
    ("AXISBANK.NS","Axis Bank","Financials","Banks","INR","NSE"),
    ("SUNPHARMA.NS","Sun Pharma","Healthcare","Pharmaceuticals","INR","NSE"),
    ("WIPRO.NS","Wipro Ltd.","Technology","IT Services","INR","NSE"),
    ("ULTRACEMCO.NS","UltraTech Cement","Materials","Cement","INR","NSE"),
    ("TITAN.NS","Titan Company","Consumer Cyclical","Jewelry","INR","NSE"),
    ("NESTLEIND.NS","Nestle India","Consumer Defensive","Packaged Foods","INR","NSE"),
    ("BAJFINANCE.NS","Bajaj Finance","Financials","Consumer Finance","INR","NSE"),
    ("BAJAJFINSV.NS","Bajaj Finserv","Financials","Insurance","INR","NSE"),
    ("TECHM.NS","Tech Mahindra","Technology","IT Services","INR","NSE"),
    ("INDUSINDBK.NS","IndusInd Bank","Financials","Banks","INR","NSE"),
    ("POWERGRID.NS","Power Grid Corp.","Utilities","Electric Utilities","INR","NSE"),
    ("NTPC.NS","NTPC Ltd.","Utilities","Electric Utilities","INR","NSE"),
    ("ONGC.NS","Oil & Natural Gas Corp.","Energy","Oil & Gas E&P","INR","NSE"),
    ("TATAMOTORS.NS","Tata Motors","Consumer Cyclical","Auto Manufacturers","INR","NSE"),
    ("TATASTEEL.NS","Tata Steel","Materials","Steel","INR","NSE"),
    ("JSWSTEEL.NS","JSW Steel","Materials","Steel","INR","NSE"),
    ("HINDALCO.NS","Hindalco Industries","Materials","Aluminum","INR","NSE"),
    ("COALINDIA.NS","Coal India","Energy","Coal","INR","NSE"),
    ("BPCL.NS","BPCL","Energy","Oil & Gas Refining","INR","NSE"),
    ("GRASIM.NS","Grasim Industries","Materials","Diversified","INR","NSE"),
    ("CIPLA.NS","Cipla Ltd.","Healthcare","Pharmaceuticals","INR","NSE"),
    ("DRREDDY.NS","Dr. Reddy's Labs","Healthcare","Pharmaceuticals","INR","NSE"),
    ("DIVISLAB.NS","Divi's Laboratories","Healthcare","Pharmaceuticals","INR","NSE"),
    ("EICHERMOT.NS","Eicher Motors","Consumer Cyclical","Auto Manufacturers","INR","NSE"),
    ("HEROMOTOCO.NS","Hero MotoCorp","Consumer Cyclical","Auto Manufacturers","INR","NSE"),
    ("BAJAJ-AUTO.NS","Bajaj Auto","Consumer Cyclical","Auto Manufacturers","INR","NSE"),
    ("BRITANNIA.NS","Britannia Industries","Consumer Defensive","Packaged Foods","INR","NSE"),
    ("SHREECEM.NS","Shree Cement","Materials","Cement","INR","NSE"),
    ("ADANIPORTS.NS","Adani Ports","Industrials","Ports","INR","NSE"),
    ("ADANIENT.NS","Adani Enterprises","Industrials","Conglomerates","INR","NSE"),
    ("ADANIGREEN.NS","Adani Green Energy","Utilities","Renewable Energy","INR","NSE"),
    ("ADANIPOWER.NS","Adani Power","Utilities","Electric Utilities","INR","NSE"),
    ("TATACONSUM.NS","Tata Consumer Products","Consumer Defensive","Packaged Foods","INR","NSE"),
    ("APOLLOHOSP.NS","Apollo Hospitals","Healthcare","Hospital Operators","INR","NSE"),
    ("PIDILITIND.NS","Pidilite Industries","Materials","Specialty Chemicals","INR","NSE"),
    ("BERGEPAINT.NS","Berger Paints","Materials","Specialty Chemicals","INR","NSE"),
    ("HAL.NS","Hindustan Aeronautics","Industrials","Aerospace & Defense","INR","NSE"),
    ("BEL.NS","Bharat Electronics","Industrials","Electronics","INR","NSE"),
    ("SIEMENS.NS","Siemens India","Industrials","Industrial Machinery","INR","NSE"),
    ("ABB.NS","ABB India","Industrials","Electrical Equipment","INR","NSE"),
    ("CHOLAFIN.NS","Cholamandalam Finance","Financials","Consumer Finance","INR","NSE"),
    ("MUTHOOTFIN.NS","Muthoot Finance","Financials","Consumer Finance","INR","NSE"),
    ("PNB.NS","Punjab National Bank","Financials","Banks","INR","NSE"),
    ("BANKBARODA.NS","Bank of Baroda","Financials","Banks","INR","NSE"),
    ("CANBK.NS","Canara Bank","Financials","Banks","INR","NSE"),
    ("HDFCLIFE.NS","HDFC Life Insurance","Financials","Insurance","INR","NSE"),
    ("SBILIFE.NS","SBI Life Insurance","Financials","Insurance","INR","NSE"),
    ("ICICIPRULI.NS","ICICI Prudential Life","Financials","Insurance","INR","NSE"),
    ("VEDL.NS","Vedanta Ltd.","Materials","Diversified Metals","INR","NSE"),
    ("NMDC.NS","NMDC Ltd.","Materials","Iron Ore","INR","NSE"),
    ("SAIL.NS","Steel Authority of India","Materials","Steel","INR","NSE"),
    ("ICICIGI.NS","ICICI Lombard General","Financials","Insurance","INR","NSE"),
    ("GODREJCP.NS","Godrej Consumer Products","Consumer Defensive","Household Products","INR","NSE"),
    ("MARICO.NS","Marico Ltd.","Consumer Defensive","Personal Products","INR","NSE"),
    ("COLPAL.NS","Colgate-Palmolive India","Consumer Defensive","Household Products","INR","NSE"),
    ("DABUR.NS","Dabur India","Consumer Defensive","Personal Products","INR","NSE"),
    ("EMAMILTD.NS","Emami Ltd.","Consumer Defensive","Personal Products","INR","NSE"),
    ("DMART.NS","Avenue Supermarts (D-Mart)","Consumer Defensive","Discount Stores","INR","NSE"),
    ("TRENT.NS","Trent Ltd.","Consumer Cyclical","Apparel Retail","INR","NSE"),
    ("PAGEIND.NS","Page Industries","Consumer Cyclical","Apparel Manufacturing","INR","NSE"),
    ("MPHASIS.NS","Mphasis Ltd.","Technology","IT Services","INR","NSE"),
    ("LTIM.NS","LTIMindtree","Technology","IT Services","INR","NSE"),
    ("PERSISTENT.NS","Persistent Systems","Technology","IT Services","INR","NSE"),
    ("COFORGE.NS","Coforge Ltd.","Technology","IT Services","INR","NSE"),
    ("NAUKRI.NS","Info Edge (India)","Technology","Internet","INR","NSE"),
    ("ZOMATO.NS","Zomato Ltd.","Consumer Cyclical","Food Delivery","INR","NSE"),
    ("PAYTM.NS","One 97 Communications","Financials","Fintech","INR","NSE"),
    ("IRCTC.NS","IRCTC","Consumer Cyclical","Travel Services","INR","NSE"),
    ("INDIGO.NS","InterGlobe Aviation","Industrials","Airlines","INR","NSE"),
    ("GAIL.NS","GAIL India","Energy","Gas Distribution","INR","NSE"),
    ("IOC.NS","Indian Oil Corp.","Energy","Oil & Gas Refining","INR","NSE"),
    ("MRF.NS","MRF Ltd.","Consumer Cyclical","Auto Parts","INR","NSE"),
    ("APOLLOTYRE.NS","Apollo Tyres","Consumer Cyclical","Auto Parts","INR","NSE"),
    ("TORNTPHARM.NS","Torrent Pharma","Healthcare","Pharmaceuticals","INR","NSE"),
    ("LUPIN.NS","Lupin Ltd.","Healthcare","Pharmaceuticals","INR","NSE"),
    ("AUROPHARMA.NS","Aurobindo Pharma","Healthcare","Pharmaceuticals","INR","NSE"),
    ("BIOCON.NS","Biocon Ltd.","Healthcare","Biotechnology","INR","NSE"),
    ("NYKAA.NS","FSN E-Commerce (Nykaa)","Consumer Cyclical","E-Commerce","INR","NSE"),
    ("POLICYBZR.NS","PB Fintech (Policybazaar)","Financials","Fintech","INR","NSE"),
    ("BANDHANBNK.NS","Bandhan Bank","Financials","Banks","INR","NSE"),
    ("IDFCFIRSTB.NS","IDFC First Bank","Financials","Banks","INR","NSE"),
    ("FEDERALBNK.NS","Federal Bank","Financials","Banks","INR","NSE"),
    ("RBLBANK.NS","RBL Bank","Financials","Banks","INR","NSE"),
    ("YESBANK.NS","Yes Bank","Financials","Banks","INR","NSE"),
]

UK_STOCKS = [
    ("AZN.L","AstraZeneca","Healthcare","Pharmaceuticals","GBP","LSE"),
    ("SHEL.L","Shell plc","Energy","Oil & Gas Integrated","GBP","LSE"),
    ("HSBA.L","HSBC Holdings","Financials","Banks","GBP","LSE"),
    ("ULVR.L","Unilever plc","Consumer Defensive","Household Products","GBP","LSE"),
    ("BP.L","BP plc","Energy","Oil & Gas Integrated","GBP","LSE"),
    ("GSK.L","GSK plc","Healthcare","Pharmaceuticals","GBP","LSE"),
    ("RIO.L","Rio Tinto","Materials","Diversified Metals","GBP","LSE"),
    ("BHP.L","BHP Group","Materials","Diversified Metals","GBP","LSE"),
    ("DGE.L","Diageo plc","Consumer Defensive","Beverages-Alcohol","GBP","LSE"),
    ("REL.L","RELX plc","Communication Services","Data Analytics","GBP","LSE"),
    ("NG.L","National Grid","Utilities","Electric Utilities","GBP","LSE"),
    ("RKT.L","Reckitt Benckiser","Consumer Defensive","Household Products","GBP","LSE"),
    ("EXPN.L","Experian plc","Financials","Financial Data","GBP","LSE"),
    ("CPG.L","Compass Group","Consumer Cyclical","Food Services","GBP","LSE"),
    ("STAN.L","Standard Chartered","Financials","Banks","GBP","LSE"),
    ("NWG.L","NatWest Group","Financials","Banks","GBP","LSE"),
    ("LLOY.L","Lloyds Banking Group","Financials","Banks","GBP","LSE"),
    ("BARC.L","Barclays plc","Financials","Banks","GBP","LSE"),
    ("ABF.L","Associated British Foods","Consumer Defensive","Food Producers","GBP","LSE"),
    ("TSCO.L","Tesco plc","Consumer Defensive","Grocery Stores","GBP","LSE"),
    ("IMB.L","Imperial Brands","Consumer Defensive","Tobacco","GBP","LSE"),
    ("BATS.L","British American Tobacco","Consumer Defensive","Tobacco","GBP","LSE"),
    ("VOD.L","Vodafone Group","Communication Services","Telecom","GBP","LSE"),
    ("BT.A.L","BT Group","Communication Services","Telecom","GBP","LSE"),
    ("PSON.L","Pearson plc","Communication Services","Publishing","GBP","LSE"),
    ("IHG.L","InterContinental Hotels","Consumer Cyclical","Hotels","GBP","LSE"),
    ("WPP.L","WPP plc","Communication Services","Advertising","GBP","LSE"),
    ("JET2.L","Jet2 plc","Consumer Cyclical","Airlines","GBP","LSE"),
    ("IAG.L","International Airlines Group","Industrials","Airlines","GBP","LSE"),
    ("RR.L","Rolls-Royce Holdings","Industrials","Aerospace Engines","GBP","LSE"),
    ("BA.L","BAE Systems","Industrials","Aerospace & Defense","GBP","LSE"),
    ("WEIR.L","Weir Group","Industrials","Industrial Machinery","GBP","LSE"),
    ("SGRO.L","Segro plc","Real Estate","Industrial REITs","GBP","LSE"),
    ("LND.L","Land Securities","Real Estate","Diversified REITs","GBP","LSE"),
    ("MNDI.L","Mondi plc","Materials","Packaging","GBP","LSE"),
    ("SMDS.L","DS Smith","Materials","Packaging","GBP","LSE"),
    ("CRH.L","CRH plc","Materials","Construction Materials","GBP","LSE"),
    ("EZJ.L","easyJet plc","Industrials","Airlines","GBP","LSE"),
    ("GLEN.L","Glencore plc","Materials","Diversified Metals","GBP","LSE"),
    ("AAL.L","Anglo American","Materials","Diversified Metals","GBP","LSE"),
    ("FRES.L","Fresnillo plc","Materials","Silver/Gold Mining","GBP","LSE"),
    ("EVR.L","Endeavour Mining","Materials","Gold","GBP","LSE"),
    ("DPLM.L","Diploma plc","Industrials","Distribution","GBP","LSE"),
    ("SDR.L","Schroders plc","Financials","Asset Management","GBP","LSE"),
    ("HL.L","Hargreaves Lansdown","Financials","Brokerage","GBP","LSE"),
    ("LGEN.L","Legal & General","Financials","Insurance","GBP","LSE"),
    ("AV.L","Aviva plc","Financials","Insurance","GBP","LSE"),
    ("PRU.L","Prudential plc","Financials","Insurance","GBP","LSE"),
    ("JUST.L","Just Group","Financials","Insurance","GBP","LSE"),
    ("MNG.L","M&G plc","Financials","Asset Management","GBP","LSE"),
    ("SBRY.L","Sainsbury's","Consumer Defensive","Grocery Stores","GBP","LSE"),
    ("MKS.L","Marks & Spencer","Consumer Cyclical","Apparel Retail","GBP","LSE"),
    ("NEXT.L","Next plc","Consumer Cyclical","Apparel Retail","GBP","LSE"),
    ("SPX.L","Spirax Group","Industrials","Industrial Machinery","GBP","LSE"),
    ("IMI.L","IMI plc","Industrials","Industrial Machinery","GBP","LSE"),
    ("SN.L","Smith & Nephew","Healthcare","Medical Devices","GBP","LSE"),
    ("UU.L","United Utilities","Utilities","Water Utilities","GBP","LSE"),
    ("SVT.L","Severn Trent","Utilities","Water Utilities","GBP","LSE"),
    ("CNA.L","Centrica plc","Utilities","Electric Utilities","GBP","LSE"),
    ("DRX.L","Drax Group","Utilities","Electric Utilities","GBP","LSE"),
    ("SSE.L","SSE plc","Utilities","Electric Utilities","GBP","LSE"),
    ("SXS.L","Spectris plc","Industrials","Test Equipment","GBP","LSE"),
    ("HLMA.L","Halma plc","Industrials","Safety Equipment","GBP","LSE"),
    ("RTO.L","Rentokil Initial","Industrials","Business Services","GBP","LSE"),
    ("BDEV.L","Barratt Developments","Consumer Cyclical","Home Construction","GBP","LSE"),
    ("PSN.L","Persimmon plc","Consumer Cyclical","Home Construction","GBP","LSE"),
    ("TW.L","Taylor Wimpey","Consumer Cyclical","Home Construction","GBP","LSE"),
    ("LAND.L","Land Securities","Real Estate","Commercial REITs","GBP","LSE"),
    ("BLND.L","British Land","Real Estate","Commercial REITs","GBP","LSE"),
    ("PHP.L","PHP plc","Real Estate","Healthcare REITs","GBP","LSE"),
    ("BBOX.L","Tritax Big Box REIT","Real Estate","Industrial REITs","GBP","LSE"),
    ("DCC.L","DCC plc","Industrials","Distribution","GBP","LSE"),
    ("OCDO.L","Ocado Group","Consumer Defensive","Online Grocery","GBP","LSE"),
    ("AUTO.L","Auto Trader Group","Communication Services","Online Auto","GBP","LSE"),
    ("RMV.L","Rightmove plc","Communication Services","Online Real Estate","GBP","LSE"),
]

CANADA_STOCKS = [
    ("RY.TO","Royal Bank of Canada","Financials","Banks","CAD","TSX"),
    ("TD.TO","Toronto-Dominion Bank","Financials","Banks","CAD","TSX"),
    ("BNS.TO","Bank of Nova Scotia","Financials","Banks","CAD","TSX"),
    ("BMO.TO","Bank of Montreal","Financials","Banks","CAD","TSX"),
    ("CM.TO","CIBC","Financials","Banks","CAD","TSX"),
    ("ENB.TO","Enbridge Inc.","Energy","Oil & Gas Pipelines","CAD","TSX"),
    ("CNQ.TO","Canadian Natural Resources","Energy","Oil & Gas E&P","CAD","TSX"),
    ("SU.TO","Suncor Energy","Energy","Oil & Gas Integrated","CAD","TSX"),
    ("TRP.TO","TC Energy","Energy","Oil & Gas Pipelines","CAD","TSX"),
    ("IMO.TO","Imperial Oil","Energy","Oil & Gas Integrated","CAD","TSX"),
    ("WCP.TO","Whitecap Resources","Energy","Oil & Gas E&P","CAD","TSX"),
    ("CVE.TO","Cenovus Energy","Energy","Oil & Gas Integrated","CAD","TSX"),
    ("MFC.TO","Manulife Financial","Financials","Insurance","CAD","TSX"),
    ("SLF.TO","Sun Life Financial","Financials","Insurance","CAD","TSX"),
    ("GWO.TO","Great-West Lifeco","Financials","Insurance","CAD","TSX"),
    ("BAM.TO","Brookfield Asset Mgmt","Financials","Asset Management","CAD","TSX"),
    ("BN.TO","Brookfield Corp.","Financials","Diversified Financial","CAD","TSX"),
    ("FFH.TO","Fairfax Financial","Financials","Insurance","CAD","TSX"),
    ("SHOP.TO","Shopify Inc.","Technology","E-Commerce Software","CAD","TSX"),
    ("CSU.TO","Constellation Software","Technology","Software","CAD","TSX"),
    ("OTEX.TO","Open Text Corp.","Technology","Software","CAD","TSX"),
    ("CGI.TO","CGI Inc.","Technology","IT Services","CAD","TSX"),
    ("GIB.A.TO","CGI Inc. A","Technology","IT Services","CAD","TSX"),
    ("TRI.TO","Thomson Reuters","Communication Services","Data Analytics","CAD","TSX"),
    ("BCE.TO","BCE Inc.","Communication Services","Telecom","CAD","TSX"),
    ("T.TO","TELUS Corp.","Communication Services","Telecom","CAD","TSX"),
    ("RCI.B.TO","Rogers Communications","Communication Services","Telecom","CAD","TSX"),
    ("QBR.B.TO","Quebecor","Communication Services","Telecom","CAD","TSX"),
    ("ABX.TO","Barrick Gold","Materials","Gold","CAD","TSX"),
    ("AEM.TO","Agnico Eagle Mines","Materials","Gold","CAD","TSX"),
    ("K.TO","Kinross Gold","Materials","Gold","CAD","TSX"),
    ("FM.TO","First Quantum Minerals","Materials","Copper","CAD","TSX"),
    ("CS.TO","Capstone Copper","Materials","Copper","CAD","TSX"),
    ("TECK.B.TO","Teck Resources","Materials","Diversified Metals","CAD","TSX"),
    ("CCO.TO","Cameco Corp.","Energy","Uranium","CAD","TSX"),
    ("NTR.TO","Nutrien Ltd.","Materials","Agricultural Chemicals","CAD","TSX"),
    ("CP.TO","Canadian Pacific Kansas City","Industrials","Railroads","CAD","TSX"),
    ("CNR.TO","Canadian National Railway","Industrials","Railroads","CAD","TSX"),
    ("WN.TO","George Weston","Consumer Defensive","Food Producers","CAD","TSX"),
    ("L.TO","Loblaw Companies","Consumer Defensive","Grocery Stores","CAD","TSX"),
    ("EMP.A.TO","Empire Company","Consumer Defensive","Grocery Stores","CAD","TSX"),
    ("ATD.TO","Alimentation Couche-Tard","Consumer Defensive","Gas Stations","CAD","TSX"),
    ("MRU.TO","Metro Inc.","Consumer Defensive","Grocery Stores","CAD","TSX"),
    ("POW.TO","Power Corp. of Canada","Financials","Diversified Financial","CAD","TSX"),
    ("IFC.TO","Intact Financial","Financials","Insurance","CAD","TSX"),
    ("X.TO","TMX Group","Financials","Exchanges","CAD","TSX"),
    ("EQB.TO","EQB Inc.","Financials","Banks","CAD","TSX"),
    ("AC.TO","Air Canada","Industrials","Airlines","CAD","TSX"),
    ("CAE.TO","CAE Inc.","Industrials","Aerospace & Defense","CAD","TSX"),
    ("TIH.TO","Toromont Industries","Industrials","Industrial Machinery","CAD","TSX"),
]

GERMANY_STOCKS = [
    ("SAP.DE","SAP SE","Technology","Software","EUR","XETRA"),
    ("SIE.DE","Siemens AG","Industrials","Conglomerates","EUR","XETRA"),
    ("ALV.DE","Allianz SE","Financials","Insurance","EUR","XETRA"),
    ("DTE.DE","Deutsche Telekom","Communication Services","Telecom","EUR","XETRA"),
    ("BMW.DE","BMW AG","Consumer Cyclical","Auto Manufacturers","EUR","XETRA"),
    ("MBG.DE","Mercedes-Benz Group","Consumer Cyclical","Auto Manufacturers","EUR","XETRA"),
    ("VOW3.DE","Volkswagen AG","Consumer Cyclical","Auto Manufacturers","EUR","XETRA"),
    ("MRK.DE","Merck KGaA","Healthcare","Pharmaceuticals","EUR","XETRA"),
    ("BAYN.DE","Bayer AG","Healthcare","Pharmaceuticals","EUR","XETRA"),
    ("EOAN.DE","E.ON SE","Utilities","Electric Utilities","EUR","XETRA"),
    ("RWE.DE","RWE AG","Utilities","Electric Utilities","EUR","XETRA"),
    ("ADS.DE","Adidas AG","Consumer Cyclical","Footwear","EUR","XETRA"),
    ("HEN3.DE","Henkel AG","Consumer Defensive","Household Products","EUR","XETRA"),
    ("BAS.DE","BASF SE","Materials","Specialty Chemicals","EUR","XETRA"),
    ("CON.DE","Continental AG","Consumer Cyclical","Auto Parts","EUR","XETRA"),
    ("DB1.DE","Deutsche Boerse","Financials","Exchanges","EUR","XETRA"),
    ("DBK.DE","Deutsche Bank","Financials","Banks","EUR","XETRA"),
    ("CBK.DE","Commerzbank","Financials","Banks","EUR","XETRA"),
    ("MUV2.DE","Munich Re","Financials","Reinsurance","EUR","XETRA"),
    ("HNR1.DE","Hannover Re","Financials","Reinsurance","EUR","XETRA"),
    ("FRE.DE","Fresenius SE","Healthcare","Hospital Operators","EUR","XETRA"),
    ("FME.DE","Fresenius Medical Care","Healthcare","Medical Devices","EUR","XETRA"),
    ("HAG.DE","Hensoldt AG","Industrials","Aerospace & Defense","EUR","XETRA"),
    ("AIR.DE","Airbus SE","Industrials","Aerospace & Defense","EUR","XETRA"),
    ("RHM.DE","Rheinmetall AG","Industrials","Aerospace & Defense","EUR","XETRA"),
    ("MTX.DE","MTU Aero Engines","Industrials","Aerospace Engines","EUR","XETRA"),
    ("DHL.DE","DHL Group","Industrials","Delivery Services","EUR","XETRA"),
    ("HFG.DE","HelloFresh","Consumer Cyclical","Food Delivery","EUR","XETRA"),
    ("ZAL.DE","Zalando SE","Consumer Cyclical","E-Commerce","EUR","XETRA"),
    ("PUM.DE","Puma SE","Consumer Cyclical","Footwear","EUR","XETRA"),
    ("DHER.DE","Delivery Hero","Consumer Cyclical","Food Delivery","EUR","XETRA"),
    ("IFX.DE","Infineon Technologies","Technology","Semiconductors","EUR","XETRA"),
    ("AIXA.DE","Aixtron SE","Technology","Semiconductor Equipment","EUR","XETRA"),
    ("XONA.DE","Carl Zeiss Meditec","Healthcare","Medical Devices","EUR","XETRA"),
    ("SHL.DE","Siemens Healthineers","Healthcare","Medical Devices","EUR","XETRA"),
    ("EVT.DE","Evotec SE","Healthcare","Biotechnology","EUR","XETRA"),
    ("QIA.DE","Qiagen NV","Healthcare","Diagnostics","EUR","XETRA"),
    ("VNA.DE","Vonovia SE","Real Estate","Diversified REITs","EUR","XETRA"),
    ("LEG.DE","LEG Immobilien","Real Estate","Apartment REITs","EUR","XETRA"),
    ("1COV.DE","Covestro AG","Materials","Specialty Chemicals","EUR","XETRA"),
    ("WACKER.DE","Wacker Chemie","Materials","Specialty Chemicals","EUR","XETRA"),
    ("K+S.DE","K+S AG","Materials","Agricultural Chemicals","EUR","XETRA"),
    ("TKA.DE","thyssenkrupp","Materials","Steel","EUR","XETRA"),
    ("HAB.DE","Hawesko Holding","Consumer Defensive","Beverages","EUR","XETRA"),
    ("PSAN.DE","Dr. Ing. h.c. F. Porsche","Consumer Cyclical","Auto Manufacturers","EUR","XETRA"),
    ("PAH3.DE","Porsche Automobil Holding","Consumer Cyclical","Auto Manufacturers","EUR","XETRA"),
    ("SOW.DE","Software AG","Technology","Software","EUR","XETRA"),
    ("ENR.DE","Siemens Energy","Utilities","Energy Equipment","EUR","XETRA"),
    ("PFV.DE","Pfeiffer Vacuum","Industrials","Industrial Machinery","EUR","XETRA"),
    ("NDX1.DE","Nordex SE","Industrials","Wind Energy","EUR","XETRA"),
]

FRANCE_STOCKS = [
    ("MC.PA","LVMH Moët Hennessy","Consumer Cyclical","Luxury Goods","EUR","EPA"),
    ("OR.PA","L'Oréal SA","Consumer Defensive","Cosmetics","EUR","EPA"),
    ("RMS.PA","Hermès International","Consumer Cyclical","Luxury Goods","EUR","EPA"),
    ("TTE.PA","TotalEnergies","Energy","Oil & Gas Integrated","EUR","EPA"),
    ("SAN.PA","Sanofi SA","Healthcare","Pharmaceuticals","EUR","EPA"),
    ("BNP.PA","BNP Paribas","Financials","Banks","EUR","EPA"),
    ("AI.PA","Air Liquide","Materials","Industrial Gases","EUR","EPA"),
    ("AXA.PA","AXA SA","Financials","Insurance","EUR","EPA"),
    ("CS.PA","AXA SA","Financials","Insurance","EUR","EPA"),
    ("SU.PA","Schneider Electric","Industrials","Electrical Equipment","EUR","EPA"),
    ("DG.PA","Vinci SA","Industrials","Engineering & Construction","EUR","EPA"),
    ("KER.PA","Kering SA","Consumer Cyclical","Luxury Goods","EUR","EPA"),
    ("EL.PA","EssilorLuxottica","Consumer Cyclical","Eyewear","EUR","EPA"),
    ("SGO.PA","Compagnie de Saint-Gobain","Materials","Construction Materials","EUR","EPA"),
    ("CAP.PA","Capgemini SE","Technology","IT Services","EUR","EPA"),
    ("DSY.PA","Dassault Systèmes","Technology","Software","EUR","EPA"),
    ("STM.PA","STMicroelectronics","Technology","Semiconductors","EUR","EPA"),
    ("GLE.PA","Société Générale","Financials","Banks","EUR","EPA"),
    ("ACA.PA","Crédit Agricole","Financials","Banks","EUR","EPA"),
    ("ENGI.PA","Engie SA","Utilities","Electric Utilities","EUR","EPA"),
    ("ORA.PA","Orange SA","Communication Services","Telecom","EUR","EPA"),
    ("VIE.PA","Veolia Environment","Utilities","Water Utilities","EUR","EPA"),
    ("RNO.PA","Renault SA","Consumer Cyclical","Auto Manufacturers","EUR","EPA"),
    ("UG.PA","Peugeot SA (Stellantis)","Consumer Cyclical","Auto Manufacturers","EUR","EPA"),
    ("AM.PA","Dassault Aviation","Industrials","Aerospace & Defense","EUR","EPA"),
    ("HO.PA","Thales SA","Industrials","Aerospace & Defense","EUR","EPA"),
    ("SAF.PA","Safran SA","Industrials","Aerospace Engines","EUR","EPA"),
    ("BOL.PA","Bollore SE","Industrials","Logistics","EUR","EPA"),
    ("PUB.PA","Publicis Groupe","Communication Services","Advertising","EUR","EPA"),
    ("VIV.PA","Vivendi SE","Communication Services","Media","EUR","EPA"),
    ("BIM.PA","BioMérieux SA","Healthcare","Diagnostics","EUR","EPA"),
    ("ERM.PA","Eurofins Scientific","Healthcare","Testing Services","EUR","EPA"),
    ("IPN.PA","Ipsen SA","Healthcare","Pharmaceuticals","EUR","EPA"),
    ("ERF.PA","Eurazeo SE","Financials","Private Equity","EUR","EPA"),
    ("AMUN.PA","Amundi SA","Financials","Asset Management","EUR","EPA"),
    ("OPM.PA","OPmobility","Consumer Cyclical","Auto Parts","EUR","EPA"),
    ("AF.PA","Air France-KLM","Industrials","Airlines","EUR","EPA"),
    ("ADP.PA","Aéroports de Paris","Industrials","Airports","EUR","EPA"),
    ("URW.PA","Unibail-Rodamco-Westfield","Real Estate","Mall REITs","EUR","EPA"),
    ("COVIVIO.PA","Covivio SA","Real Estate","Diversified REITs","EUR","EPA"),
]

JAPAN_STOCKS = [
    ("7203.T","Toyota Motor","Consumer Cyclical","Auto Manufacturers","JPY","TSE"),
    ("6758.T","Sony Group","Consumer Cyclical","Electronics","JPY","TSE"),
    ("9984.T","SoftBank Group","Communication Services","Telecom","JPY","TSE"),
    ("7974.T","Nintendo Co.","Consumer Cyclical","Video Games","JPY","TSE"),
    ("6861.T","Keyence Corp.","Technology","Industrial Sensors","JPY","TSE"),
    ("8306.T","Mitsubishi UFJ Financial","Financials","Banks","JPY","TSE"),
    ("9432.T","Nippon Telegraph & Tel.","Communication Services","Telecom","JPY","TSE"),
    ("4519.T","Chugai Pharmaceutical","Healthcare","Pharmaceuticals","JPY","TSE"),
    ("6367.T","Daikin Industries","Industrials","HVAC","JPY","TSE"),
    ("7267.T","Honda Motor","Consumer Cyclical","Auto Manufacturers","JPY","TSE"),
    ("8316.T","Sumitomo Mitsui Financial","Financials","Banks","JPY","TSE"),
    ("6954.T","Fanuc Corp.","Industrials","Industrial Robots","JPY","TSE"),
    ("4523.T","Eisai Co.","Healthcare","Pharmaceuticals","JPY","TSE"),
    ("4568.T","Daiichi Sankyo","Healthcare","Pharmaceuticals","JPY","TSE"),
    ("4502.T","Takeda Pharmaceutical","Healthcare","Pharmaceuticals","JPY","TSE"),
    ("9433.T","KDDI Corp.","Communication Services","Telecom","JPY","TSE"),
    ("8411.T","Mizuho Financial Group","Financials","Banks","JPY","TSE"),
    ("8058.T","Mitsubishi Corp.","Industrials","Trading Companies","JPY","TSE"),
    ("8031.T","Mitsui & Co.","Industrials","Trading Companies","JPY","TSE"),
    ("8053.T","Sumitomo Corp.","Industrials","Trading Companies","JPY","TSE"),
    ("8001.T","Itochu Corp.","Industrials","Trading Companies","JPY","TSE"),
    ("8002.T","Marubeni Corp.","Industrials","Trading Companies","JPY","TSE"),
    ("7741.T","Hoya Corp.","Healthcare","Medical Devices","JPY","TSE"),
    ("6920.T","Lasertec Corp.","Technology","Semiconductor Equipment","JPY","TSE"),
    ("4661.T","Oriental Land","Consumer Cyclical","Theme Parks","JPY","TSE"),
    ("9983.T","Fast Retailing","Consumer Cyclical","Apparel Retail","JPY","TSE"),
    ("3382.T","Seven & I Holdings","Consumer Defensive","Convenience Stores","JPY","TSE"),
    ("2914.T","Japan Tobacco","Consumer Defensive","Tobacco","JPY","TSE"),
    ("2802.T","Ajinomoto Co.","Consumer Defensive","Packaged Foods","JPY","TSE"),
    ("7751.T","Canon Inc.","Technology","Imaging","JPY","TSE"),
    ("6501.T","Hitachi Ltd.","Industrials","Conglomerates","JPY","TSE"),
    ("6702.T","Fujitsu Ltd.","Technology","IT Services","JPY","TSE"),
    ("6752.T","Panasonic Holdings","Consumer Cyclical","Electronics","JPY","TSE"),
    ("6971.T","Kyocera Corp.","Technology","Electronic Components","JPY","TSE"),
    ("4452.T","Kao Corp.","Consumer Defensive","Personal Products","JPY","TSE"),
    ("7733.T","Olympus Corp.","Healthcare","Medical Devices","JPY","TSE"),
    ("2503.T","Kirin Holdings","Consumer Defensive","Beverages","JPY","TSE"),
    ("2502.T","Asahi Group Holdings","Consumer Defensive","Beverages","JPY","TSE"),
    ("3407.T","Asahi Kasei","Materials","Specialty Chemicals","JPY","TSE"),
    ("3086.T","J. Front Retailing","Consumer Cyclical","Department Stores","JPY","TSE"),
    ("8830.T","Sumitomo Realty","Real Estate","Diversified REITs","JPY","TSE"),
    ("3289.T","Tokyu Fudosan Holdings","Real Estate","Diversified REITs","JPY","TSE"),
    ("9022.T","Central Japan Railway","Industrials","Railroads","JPY","TSE"),
    ("9020.T","East Japan Railway","Industrials","Railroads","JPY","TSE"),
    ("9021.T","West Japan Railway","Industrials","Railroads","JPY","TSE"),
    ("5108.T","Bridgestone Corp.","Consumer Cyclical","Auto Parts","JPY","TSE"),
    ("7011.T","Mitsubishi Heavy Industries","Industrials","Aerospace & Defense","JPY","TSE"),
    ("6326.T","Kubota Corp.","Industrials","Farm Equipment","JPY","TSE"),
    ("5401.T","Nippon Steel","Materials","Steel","JPY","TSE"),
    ("5411.T","JFE Holdings","Materials","Steel","JPY","TSE"),
]

HONGKONG_STOCKS = [
    ("0700.HK","Tencent Holdings","Communication Services","Internet Content","HKD","HKEX"),
    ("0939.HK","China Construction Bank","Financials","Banks","HKD","HKEX"),
    ("1398.HK","Industrial & Commercial Bank","Financials","Banks","HKD","HKEX"),
    ("3988.HK","Bank of China","Financials","Banks","HKD","HKEX"),
    ("0005.HK","HSBC Holdings","Financials","Banks","HKD","HKEX"),
    ("0941.HK","China Mobile","Communication Services","Telecom","HKD","HKEX"),
    ("1810.HK","Xiaomi Corp.","Consumer Cyclical","Electronics","HKD","HKEX"),
    ("9988.HK","Alibaba Group","Consumer Cyclical","E-Commerce","HKD","HKEX"),
    ("3690.HK","Meituan","Consumer Cyclical","Food Delivery","HKD","HKEX"),
    ("2318.HK","Ping An Insurance","Financials","Insurance","HKD","HKEX"),
    ("1177.HK","Sino Biopharmaceutical","Healthcare","Pharmaceuticals","HKD","HKEX"),
    ("2269.HK","WuXi Biologics","Healthcare","Biologics","HKD","HKEX"),
    ("6098.HK","Country Garden Services","Real Estate","Property Mgmt","HKD","HKEX"),
    ("1109.HK","China Resources Land","Real Estate","Real Estate","HKD","HKEX"),
    ("1997.HK","Wharf Real Estate","Real Estate","Real Estate","HKD","HKEX"),
    ("0016.HK","Sun Hung Kai Properties","Real Estate","Real Estate","HKD","HKEX"),
    ("0001.HK","CK Hutchison Holdings","Industrials","Conglomerates","HKD","HKEX"),
    ("0002.HK","CLP Holdings","Utilities","Electric Utilities","HKD","HKEX"),
    ("0003.HK","HK & China Gas","Utilities","Gas Utilities","HKD","HKEX"),
    ("0006.HK","Power Assets Holdings","Utilities","Electric Utilities","HKD","HKEX"),
    ("0012.HK","Henderson Land Dev.","Real Estate","Real Estate","HKD","HKEX"),
    ("0011.HK","Hang Seng Bank","Financials","Banks","HKD","HKEX"),
    ("2388.HK","BOC Hong Kong","Financials","Banks","HKD","HKEX"),
    ("1038.HK","CK Infrastructure","Utilities","Infrastructure","HKD","HKEX"),
    ("0066.HK","MTR Corporation","Industrials","Railroads","HKD","HKEX"),
    ("0027.HK","Galaxy Entertainment","Consumer Cyclical","Casinos","HKD","HKEX"),
    ("1928.HK","Sands China","Consumer Cyclical","Casinos","HKD","HKEX"),
    ("0880.HK","SJM Holdings","Consumer Cyclical","Casinos","HKD","HKEX"),
    ("2020.HK","ANTA Sports Products","Consumer Cyclical","Footwear","HKD","HKEX"),
    ("1929.HK","Chow Tai Fook Jewellery","Consumer Cyclical","Jewelry","HKD","HKEX"),
    ("6862.HK","Haidilao International","Consumer Cyclical","Restaurants","HKD","HKEX"),
    ("0992.HK","Lenovo Group","Technology","Computer Hardware","HKD","HKEX"),
    ("9618.HK","JD.com","Consumer Cyclical","E-Commerce","HKD","HKEX"),
    ("9999.HK","NetEase Inc.","Communication Services","Video Games","HKD","HKEX"),
    ("6690.HK","Haier Smart Home","Consumer Cyclical","Home Appliances","HKD","HKEX"),
    ("0388.HK","HK Exchanges & Clearing","Financials","Exchanges","HKD","HKEX"),
    ("0857.HK","PetroChina","Energy","Oil & Gas Integrated","HKD","HKEX"),
    ("0386.HK","Sinopec Corp.","Energy","Oil & Gas Refining","HKD","HKEX"),
    ("1088.HK","China Shenhua Energy","Energy","Coal","HKD","HKEX"),
    ("2628.HK","China Life Insurance","Financials","Insurance","HKD","HKEX"),
]

CHINA_STOCKS = [
    ("600519.SS","Kweichow Moutai","Consumer Defensive","Beverages-Alcohol","CNY","SSE"),
    ("601318.SS","Ping An Insurance A","Financials","Insurance","CNY","SSE"),
    ("600036.SS","China Merchants Bank A","Financials","Banks","CNY","SSE"),
    ("601166.SS","Industrial Bank","Financials","Banks","CNY","SSE"),
    ("600900.SS","Yangtze Power","Utilities","Electric Utilities","CNY","SSE"),
    ("601628.SS","China Life Insurance A","Financials","Insurance","CNY","SSE"),
    ("601888.SS","China International Travel","Consumer Cyclical","Travel","CNY","SSE"),
    ("600276.SS","Hengrui Medicine","Healthcare","Pharmaceuticals","CNY","SSE"),
    ("600309.SS","Wanhua Chemical","Materials","Specialty Chemicals","CNY","SSE"),
    ("601012.SS","LONGi Green Energy","Technology","Solar","CNY","SSE"),
    ("002594.SZ","BYD Co. A","Consumer Cyclical","Auto Manufacturers","CNY","SZSE"),
    ("000858.SZ","Wuliangye Yibin","Consumer Defensive","Beverages-Alcohol","CNY","SZSE"),
    ("000333.SZ","Midea Group","Consumer Cyclical","Home Appliances","CNY","SZSE"),
    ("002415.SZ","Hikvision","Technology","Security Systems","CNY","SZSE"),
    ("300750.SZ","CATL (Contemporary Amperex)","Technology","Batteries","CNY","SZSE"),
    ("000651.SZ","Gree Electric","Consumer Cyclical","Home Appliances","CNY","SZSE"),
    ("002475.SZ","Luxshare Precision","Technology","Electronic Components","CNY","SZSE"),
    ("000568.SZ","Luzhou Laojiao","Consumer Defensive","Beverages-Alcohol","CNY","SZSE"),
    ("300015.SZ","Oriental Biotech","Healthcare","Biotechnology","CNY","SZSE"),
    ("000002.SZ","Vanke A","Real Estate","Real Estate","CNY","SZSE"),
    ("601899.SS","Zijin Mining","Materials","Gold/Copper","CNY","SSE"),
    ("600000.SS","Shanghai Pudong Development","Financials","Banks","CNY","SSE"),
    ("601601.SS","China Pacific Insurance","Financials","Insurance","CNY","SSE"),
    ("600030.SS","CITIC Securities","Financials","Brokerage","CNY","SSE"),
    ("601688.SS","Huatai Securities","Financials","Brokerage","CNY","SSE"),
    ("601186.SS","China Railway Construction","Industrials","Construction","CNY","SSE"),
    ("601668.SS","China State Construction","Industrials","Construction","CNY","SSE"),
    ("600031.SS","Sany Heavy Industry","Industrials","Heavy Equipment","CNY","SSE"),
    ("601919.SS","COSCO Shipping Holdings","Industrials","Shipping","CNY","SSE"),
    ("600104.SS","SAIC Motor","Consumer Cyclical","Auto Manufacturers","CNY","SSE"),
    ("601127.SS","Chery Automobile (Seres)","Consumer Cyclical","Auto Manufacturers","CNY","SSE"),
    ("000001.SZ","Ping An Bank","Financials","Banks","CNY","SZSE"),
    ("000063.SZ","ZTE Corp.","Technology","Telecom Equipment","CNY","SZSE"),
    ("300014.SZ","EVE Energy","Technology","Batteries","CNY","SZSE"),
    ("002049.SZ","Unigroup Guoxin Micro.","Technology","Semiconductors","CNY","SZSE"),
    ("600887.SS","Inner Mongolia Yili","Consumer Defensive","Dairy","CNY","SSE"),
    ("600690.SS","Haier Smart Home A","Consumer Cyclical","Home Appliances","CNY","SSE"),
    ("601988.SS","Bank of China A","Financials","Banks","CNY","SSE"),
    ("601658.SS","Postal Savings Bank","Financials","Banks","CNY","SSE"),
    ("600028.SS","Sinopec A","Energy","Oil & Gas Refining","CNY","SSE"),
]

KOREA_STOCKS = [
    ("005930.KS","Samsung Electronics","Technology","Semiconductors","KRW","KSC"),
    ("000660.KS","SK Hynix","Technology","Semiconductors","KRW","KSC"),
    ("207940.KS","Samsung Biologics","Healthcare","Biologics","KRW","KSC"),
    ("005380.KS","Hyundai Motor","Consumer Cyclical","Auto Manufacturers","KRW","KSC"),
    ("035420.KS","NAVER Corp.","Communication Services","Internet","KRW","KSC"),
    ("006400.KS","Samsung SDI","Technology","Batteries","KRW","KSC"),
    ("035720.KS","Kakao Corp.","Communication Services","Internet","KRW","KSC"),
    ("051910.KS","LG Chem","Materials","Specialty Chemicals","KRW","KSC"),
    ("003550.KS","LG Corp.","Industrials","Conglomerates","KRW","KSC"),
    ("096770.KS","SK Innovation","Energy","Oil & Gas Integrated","KRW","KSC"),
    ("028260.KS","Samsung C&T","Industrials","Conglomerates","KRW","KSC"),
    ("012330.KS","Hyundai Mobis","Consumer Cyclical","Auto Parts","KRW","KSC"),
    ("066570.KS","LG Electronics","Consumer Cyclical","Electronics","KRW","KSC"),
    ("032830.KS","Samsung Life Insurance","Financials","Insurance","KRW","KSC"),
    ("105560.KS","KB Financial Group","Financials","Banks","KRW","KSC"),
    ("055550.KS","Shinhan Financial","Financials","Banks","KRW","KSC"),
    ("086790.KS","Hana Financial Group","Financials","Banks","KRW","KSC"),
    ("000270.KS","Kia Corp.","Consumer Cyclical","Auto Manufacturers","KRW","KSC"),
    ("003490.KS","Korean Air Lines","Industrials","Airlines","KRW","KSC"),
    ("011200.KS","HMM Co.","Industrials","Shipping","KRW","KSC"),
]

AUSTRALIA_STOCKS = [
    ("BHP.AX","BHP Group","Materials","Diversified Metals","AUD","ASX"),
    ("CBA.AX","Commonwealth Bank","Financials","Banks","AUD","ASX"),
    ("CSL.AX","CSL Ltd.","Healthcare","Biotechnology","AUD","ASX"),
    ("NAB.AX","National Australia Bank","Financials","Banks","AUD","ASX"),
    ("WBC.AX","Westpac Banking","Financials","Banks","AUD","ASX"),
    ("ANZ.AX","ANZ Group Holdings","Financials","Banks","AUD","ASX"),
    ("MQG.AX","Macquarie Group","Financials","Asset Management","AUD","ASX"),
    ("WES.AX","Wesfarmers Ltd.","Consumer Defensive","Diversified Retail","AUD","ASX"),
    ("WOW.AX","Woolworths Group","Consumer Defensive","Grocery Stores","AUD","ASX"),
    ("RIO.AX","Rio Tinto","Materials","Diversified Metals","AUD","ASX"),
    ("FMG.AX","Fortescue Ltd.","Materials","Iron Ore","AUD","ASX"),
    ("NCM.AX","Newmont (ASX)","Materials","Gold","AUD","ASX"),
    ("TCL.AX","Transurban Group","Industrials","Infrastructure","AUD","ASX"),
    ("TLS.AX","Telstra Group","Communication Services","Telecom","AUD","ASX"),
    ("REA.AX","REA Group","Communication Services","Online Real Estate","AUD","ASX"),
    ("CAR.AX","CAR Group","Communication Services","Online Auto","AUD","ASX"),
    ("SEK.AX","SEEK Ltd.","Communication Services","Online Jobs","AUD","ASX"),
    ("COH.AX","Cochlear Ltd.","Healthcare","Medical Devices","AUD","ASX"),
    ("AMC.AX","Amcor plc","Materials","Packaging","AUD","ASX"),
    ("ALL.AX","Aristocrat Leisure","Consumer Cyclical","Gaming Machines","AUD","ASX"),
]

BRAZIL_STOCKS = [
    ("VALE3.SA","Vale SA","Materials","Iron Ore","BRL","SAO"),
    ("PETR4.SA","Petrobras PN","Energy","Oil & Gas Integrated","BRL","SAO"),
    ("PETR3.SA","Petrobras ON","Energy","Oil & Gas Integrated","BRL","SAO"),
    ("ITUB4.SA","Itaú Unibanco","Financials","Banks","BRL","SAO"),
    ("BBDC4.SA","Banco Bradesco","Financials","Banks","BRL","SAO"),
    ("BBAS3.SA","Banco do Brasil","Financials","Banks","BRL","SAO"),
    ("ABEV3.SA","Ambev SA","Consumer Defensive","Beverages-Alcohol","BRL","SAO"),
    ("WEGE3.SA","WEG SA","Industrials","Industrial Machinery","BRL","SAO"),
    ("RENT3.SA","Localiza Rent a Car","Consumer Cyclical","Car Rental","BRL","SAO"),
    ("SUZB3.SA","Suzano SA","Materials","Paper & Forest Products","BRL","SAO"),
    ("MGLU3.SA","Magazine Luiza","Consumer Cyclical","E-Commerce","BRL","SAO"),
    ("LREN3.SA","Lojas Renner","Consumer Cyclical","Apparel Retail","BRL","SAO"),
    ("HYPE3.SA","Hypera Pharma","Healthcare","Pharmaceuticals","BRL","SAO"),
    ("JBSS3.SA","JBS SA","Consumer Defensive","Meat Processing","BRL","SAO"),
    ("EMBR3.SA","Embraer SA","Industrials","Aerospace & Defense","BRL","SAO"),
]

ALL_EXCHANGES = {
    "us":        (US_STOCKS,        "United States", 300),
    "india":     (INDIA_STOCKS,     "India",         100),
    "uk":        (UK_STOCKS,        "United Kingdom", 75),
    "canada":    (CANADA_STOCKS,    "Canada",         50),
    "germany":   (GERMANY_STOCKS,   "Germany",        50),
    "france":    (FRANCE_STOCKS,    "France",         40),
    "japan":     (JAPAN_STOCKS,     "Japan",          50),
    "hongkong":  (HONGKONG_STOCKS,  "Hong Kong",      40),
    "china":     (CHINA_STOCKS,     "China",          40),
    "korea":     (KOREA_STOCKS,     "South Korea",    20),
    "australia": (AUSTRALIA_STOCKS, "Australia",      20),
    "brazil":    (BRAZIL_STOCKS,    "Brazil",         15),
}

EXCHANGE_COUNTRY_MAP = {
    "us": "US", "india": "IN", "uk": "GB", "canada": "CA",
    "germany": "DE", "france": "FR", "japan": "JP", "hongkong": "HK",
    "china": "CN", "korea": "KR", "australia": "AU", "brazil": "BR",
}


def run():
    db = SessionLocal()
    try:
        print("=" * 60)
        print("Seeding exchange_ranked_symbols + symbols_master")
        print("=" * 60)

        ers_added = ers_updated = sm_added = sm_updated = 0

        for exchange_key, (stocks, country_name, _limit) in ALL_EXCHANGES.items():
            country_code = EXCHANGE_COUNTRY_MAP[exchange_key]
            now = datetime.now(timezone.utc)

            for rank, (sym, name, sector, industry, currency, exchange_code) in enumerate(stocks, 1):
                # ── exchange_ranked_symbols ──────────────────────────────────
                existing_ers = (
                    db.query(ExchangeRankedSymbol)
                    .filter(
                        ExchangeRankedSymbol.symbol == sym,
                        ExchangeRankedSymbol.exchange_key == exchange_key,
                    )
                    .first()
                )
                if existing_ers:
                    existing_ers.name = name
                    existing_ers.sector = sector
                    existing_ers.industry = industry
                    existing_ers.rank_in_exchange = rank
                    existing_ers.is_active = True
                    existing_ers.updated_at = now
                    ers_updated += 1
                else:
                    db.add(ExchangeRankedSymbol(
                        symbol=sym,
                        name=name,
                        exchange=exchange_code,
                        exchange_key=exchange_key,
                        country=country_name,
                        currency=currency,
                        sector=sector,
                        industry=industry,
                        priority_score=1.0 - (rank / 1000),
                        rank_in_exchange=rank,
                        is_active=True,
                    ))
                    ers_added += 1

                # ── symbols_master ───────────────────────────────────────────
                existing_sm = (
                    db.query(SymbolsMaster)
                    .filter(SymbolsMaster.symbol == sym)
                    .first()
                )
                if existing_sm:
                    existing_sm.name = name
                    existing_sm.sector = sector
                    existing_sm.industry = industry
                    existing_sm.exchange = exchange_code
                    existing_sm.currency = currency
                    existing_sm.country = country_code
                    existing_sm.is_active = "Y"
                    sm_updated += 1
                else:
                    db.add(SymbolsMaster(
                        symbol=sym,
                        name=name,
                        exchange=exchange_code,
                        asset_type="Equity",
                        currency=currency,
                        country=country_code,
                        sector=sector,
                        industry=industry,
                        is_active="Y",
                    ))
                    sm_added += 1

            db.flush()
            count = len(stocks)
            print(f"  {exchange_key:12} → {count} stocks  [{country_name}]")

        db.commit()

        # Final counts
        ers_total = db.query(ExchangeRankedSymbol).filter(ExchangeRankedSymbol.is_active == True).count()
        sm_total  = db.query(SymbolsMaster).filter(SymbolsMaster.is_active == "Y").count()

        print()
        print("=" * 60)
        print(f"exchange_ranked_symbols  → added={ers_added}  updated={ers_updated}  total={ers_total}")
        print(f"symbols_master           → added={sm_added}   updated={sm_updated}   total={sm_total}")
        print("=" * 60)
        print("Done! Restart the backend server for coverage API to reflect new counts.")

    except Exception as e:
        db.rollback()
        print(f"\n✗ Fatal: {e}")
        import traceback; traceback.print_exc()
        raise
    finally:
        db.close()


if __name__ == "__main__":
    run()
