#!/bin/bash
# infra/ml-runner-userdata.sh
# Reference copy of the EC2 user data bootstrap script.
# The actual script is generated by handler.build_userdata() with per-instance env vars injected.
# This file is for documentation/debugging — keep in sync with handler.py.
set -euo pipefail

# Handle Spot interruption gracefully (EC2 sends SIGTERM 2min before reclaim)
trap 'echo "[bootstrap] SIGTERM received — Spot interrupted, shutting down"; shutdown -h now' SIGTERM SIGINT

# ── Injected by Lambda (per-instance) ────────────────────────────────────────
# export JIT_TOKEN="<github-jit-registration-token>"
# export RUNNER_INDEX="<0..N-1>"
# export TOKEN_ISSUED_AT="<unix-timestamp>"
# export S3_BUCKET="quanttrade-ml-artifacts"

# ── Token expiry guard ────────────────────────────────────────────────────────
NOW=$(date +%s)
AGE=$((NOW - TOKEN_ISSUED_AT))
if [ "$AGE" -gt 3000 ]; then
  echo "JIT token too old (${AGE}s > 3000s), aborting" >&2
  shutdown -h now
  exit 1
fi

# ── CloudWatch agent (install FIRST — logs all subsequent steps) ─────────────
cd /tmp
curl -sO https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
dpkg -i amazon-cloudwatch-agent.deb

INSTANCE_ID=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)

cat > /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json <<CW_EOF
{
  "logs": {
    "logs_collected": {
      "files": {
        "collect_list": [{
          "file_path": "/var/log/runner-bootstrap.log",
          "log_group_name": "/quanttrade/ml-runner/bootstrap",
          "log_stream_name": "${INSTANCE_ID}"
        }]
      }
    }
  }
}
CW_EOF

/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
  -a fetch-config -m ec2 -s \
  -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json

exec >> /var/log/runner-bootstrap.log 2>&1
echo "[bootstrap] Starting at $(date) | instance=${INSTANCE_ID} | runner=${RUNNER_INDEX}"

# ── System deps ───────────────────────────────────────────────────────────────
apt-get update -qq
apt-get install -y python3.12 python3.12-venv python3.12-dev git unzip awscli

# ── Restore pip/torch cache from S3 ─────────────────────────────────────────
aws s3 sync "s3://${S3_BUCKET}/runner-cache/pip/" ~/.cache/pip/ --quiet 2>/dev/null || true
aws s3 sync "s3://${S3_BUCKET}/runner-cache/torch/" /tmp/torch-cache/ --quiet 2>/dev/null || true

# ── Clone repo + install deps ────────────────────────────────────────────────
REPO="YashJoshi2109/QuantTrade-AI"
git clone --depth 1 "https://github.com/${REPO}.git" /home/runner/quanttrade
cd /home/runner/quanttrade/backend

python3.12 -m venv /home/runner/venv
source /home/runner/venv/bin/activate
pip install --cache-dir ~/.cache/pip -r requirements.txt
pip install --cache-dir /tmp/torch-cache torch --index-url https://download.pytorch.org/whl/cpu

# ── Write cache back (index 0 only — prevents Sunday 5-way race) ─────────────
if [ "$RUNNER_INDEX" -eq 0 ]; then
  echo "[bootstrap] Writing pip/torch cache to S3..."
  aws s3 sync ~/.cache/pip/ "s3://${S3_BUCKET}/runner-cache/pip/" --quiet 2>/dev/null || true
  aws s3 sync /tmp/torch-cache/ "s3://${S3_BUCKET}/runner-cache/torch/" --quiet 2>/dev/null || true
fi

# ── GHA runner binary ────────────────────────────────────────────────────────
RUNNER_DIR=/home/runner/actions-runner
mkdir -p "$RUNNER_DIR"
cd "$RUNNER_DIR"
# Try S3 mirror first (fast), fallback to GitHub releases
aws s3 cp "s3://${S3_BUCKET}/runner-cache/actions-runner-linux-x64.tar.gz" . --quiet 2>/dev/null || \
  curl -sL https://github.com/actions/runner/releases/download/v2.323.0/actions-runner-linux-x64-2.323.0.tar.gz \
       -o actions-runner-linux-x64.tar.gz
tar xzf actions-runner-linux-x64.tar.gz

# ── Register + run (--ephemeral = auto-deregister after one job) ─────────────
RUNNER_NAME="ml-spot-$(hostname)-${RUNNER_INDEX}"
./config.sh \
  --url "https://github.com/${REPO}" \
  --token "$JIT_TOKEN" \
  --labels ml \
  --name "$RUNNER_NAME" \
  --ephemeral \
  --unattended

echo "[bootstrap] Runner ${RUNNER_NAME} registered, starting job..."
./run.sh

echo "[bootstrap] Job complete, terminating instance"
shutdown -h now
